import type { Metadata } from "next";
import { Geist, Geist_Mono ,Pixelify_Sans,Inter,Jersey_10 } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";

import { ClerkProvider } from '@clerk/nextjs'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const GameFont= Jersey_10({
  variable: "--font-game",
  subsets: ["latin"],
  weight:"400"
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   //previously <ClerkProvider> was here
   <ClerkProvider>
    <html
      lang="en"
      
      className="dark"
      suppressHydrationWarning>
      
        <body className={`${geistSans.variable} ${geistMono.variable} ${GameFont.variable} ${inter.variable} antialiased`}>
         {/* <ClerkProvider> */}
        <Provider  attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange>
          {children}
        </Provider>
        {/* </ClerkProvider> */}
        </body>
    </html>
    </ClerkProvider>
    
  );
}
